use std::fs;
use std::path::{Path, PathBuf};
use tauri::Manager;

// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

// 🌟【自作コマンド1】ディスクへの物理書き込み（Rustネイティブ権限）
#[tauri::command]
fn save_project_file(app_handle: tauri::AppHandle, contents: String) -> Result<(), String> {
    // アプリ専用のローカルデータディレクトリ（AppLocalData）を取得
    let mut path = app_handle.path().app_local_data_dir()
        .map_err(|e| e.to_string())?;
    
    // ディレクトリが存在しない場合は自動生成 (mkdir -p)
    if !path.exists() {
        fs::create_dir_all(&path).map_err(|e| e.to_string())?;
    }
    
    // ファイル名「project.nova」を結合
    path.push("project.nova");
    
    // 物理書き込み実行
    fs::write(path, contents).map_err(|e| e.to_string())?;
    Ok(())
}

// 🌟【自作コマンド2】ディスクからの物理読み込み（Rustネイティブ権限）
#[tauri::command]
fn load_project_file(app_handle: tauri::AppHandle) -> Result<String, String> {
    let mut path = app_handle.path().app_local_data_dir()
        .map_err(|e| e.to_string())?;
    path.push("project.nova");
    
    if !path.exists() {
        return Err("File not found".to_string());
    }
    
    // ファイルをテキストとして直読み
    let contents = fs::read_to_string(path).map_err(|e| e.to_string())?;
    Ok(contents)
}

fn ensure_parent_dir(path: &Path) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn export_root(app_handle: &tauri::AppHandle, folder_name: &str) -> Result<PathBuf, String> {
    let mut path = app_handle
        .path()
        .app_local_data_dir()
        .map_err(|e| e.to_string())?;
    path.push("exports");
    path.push(folder_name);
    fs::create_dir_all(&path).map_err(|e| e.to_string())?;
    Ok(path)
}

#[tauri::command]
fn export_generated_java_file(app_handle: tauri::AppHandle, contents: String) -> Result<String, String> {
    let export_dir = export_root(&app_handle, "java")?;
    let file_path = export_dir.join("GeneratedMod.java");
    ensure_parent_dir(&file_path)?;
    fs::write(&file_path, contents).map_err(|e| e.to_string())?;
    Ok(file_path.to_string_lossy().to_string())
}

#[tauri::command]
fn export_forge_project(app_handle: tauri::AppHandle, contents: String, mod_id: String) -> Result<String, String> {
    let project_root = export_root(&app_handle, &format!("forge-project-{}", mod_id))?;
    let java_path = project_root
        .join("src")
        .join("main")
        .join("java")
        .join("com")
        .join("novaweave")
        .join("generated")
        .join("GeneratedMod.java");
    ensure_parent_dir(&java_path)?;
    fs::write(&java_path, contents).map_err(|e| e.to_string())?;

    let resources_root = project_root.join("src").join("main").join("resources");
    fs::create_dir_all(resources_root.join("META-INF")).map_err(|e| e.to_string())?;

    let mods_toml = format!(
        "modLoader=\"javafml\"\nloaderVersion=\"[47,)\"\nlicense=\"All Rights Reserved\"\n[[mods]]\nmodId=\"{mod_id}\"\nversion=\"1.0.0\"\ndisplayName=\"NovaWeave Generated Mod\"\ndescription=\"Generated by NovaWeave\"\n"
    );
    fs::write(resources_root.join("META-INF").join("mods.toml"), mods_toml).map_err(|e| e.to_string())?;
    fs::write(
        resources_root.join("pack.mcmeta"),
        "{\n  \"pack\": {\n    \"pack_format\": 15,\n    \"description\": \"NovaWeave generated resources\"\n  }\n}\n"
    )
    .map_err(|e| e.to_string())?;

    fs::write(
        project_root.join("build.gradle"),
        "plugins {\n    id 'java'\n}\n\ngroup = 'com.novaweave'\nversion = '1.0.0'\n\njava {\n    toolchain.languageVersion = JavaLanguageVersion.of(17)\n}\n"
    )
    .map_err(|e| e.to_string())?;
    fs::write(project_root.join("settings.gradle"), "rootProject.name = 'novaweave-generated'\n").map_err(|e| e.to_string())?;
    fs::write(
        project_root.join("gradle.properties"),
        "org.gradle.jvmargs=-Xmx2G\nminecraft_version=1.20.1\nmod_id=my_nova_mod\n"
    )
    .map_err(|e| e.to_string())?;
    fs::write(
        project_root.join("README.md"),
        "# NovaWeave Forge Export\n\nThis folder was generated by NovaWeave.\nOpen it in a Forge 1.20.1 workspace and place the Java source under `src/main/java`.\n"
    )
    .map_err(|e| e.to_string())?;

    Ok(project_root.to_string_lossy().to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        // 🌟【超重要】自作した2つのコマンドをTauriに登録！
        .invoke_handler(tauri::generate_handler![
            greet,
            save_project_file,
            load_project_file,
            export_generated_java_file,
            export_forge_project
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
